### ISSUE TITLE
Some question about making a sample input

### ISSUE THREAD

**Issue by Skygogogogo** [chennachaos/mpap#5]
If I have a solid CAD model,how to generate the immersed points and immersed integration elements.

**Comment by Skygogogogo** [comment]
And flexible solids information how to define,such as solid elements in Element-node connectivity.

**Comment by chennachaos** [comment]
I would be happy to help.
Could you please tell me about yourself?

**Comment by Skygogogogo** [comment]
Thank you for your reply. I am a graduate student in Dalian University of Technology

**Comment by chennachaos** [comment]
For 3D problems, we need a surface mesh of the solid for modelling the interface. If you have a CAD model, you can mesh the surface and use the surface triangulation as immersed elements.
You can check the cylinder3d input file for the example of flow past a fixed cylinder.

For flexible solids, we need to mesh the volume using Tetrahedron or hexahedron elements, similar to how to solve solid mechanics problems in 3D using FEM. If you provide your email ID, I will send you a sample input file for 3D flexible solid interaction.

**Comment by Skygogogogo** [comment]
Thank you very much.I get it. My email address is SSSkymail.dlut.edu.cn. Looking forward your email.

**Comment by Skygogogogo** [comment]
sorry. My email address is sssky@mail.dlut.edu.cn.

**Comment by chennachaos** [comment]
I emailed you an input file for a 3D flexible FSI problem. Since this is a 3D problem, you need to recompile the code by changing -D_DOMAIN2D to  -D_DOMAIN3D in the CMake file.

Let me know if you have any questions.
